name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Since you can choose branches when using workflow_dispatch, we need to ...
      - name: Make sure only tags are released
        if: github.ref_type != 'tag'
        run: exit 1

      - uses: actions/checkout@v4.1.6

      - uses: oven-sh/setup-bun@v1.2.2
        with:
          bun-version: 1.1.12

      - name: Install dependencies
        run: bun install

      - name: Build plugin
        run: bun run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          zip -r obsidian-create-task.zip main.js manifest.json styles.css

          gh release create ${{ github.ref_name }} \
            --title="${{ github.ref_name }}" \
            --draft \
            obsidian-create-task.zip main.js manifest.json styles.css
